export const genders: string[] = ['Male', 'Female', 'Other'];
export const relationshipStatuses: string[] = ['Single', 'Married', 'Divorced', 'Widowed', 'Other'];
export const workFeilds: string[] = [
  'Architecture',
  'Engineering',
  'Entertainment',
  'Building',
  'Business and Finance',
  'Community Services',
  'Social Services',
  'Computer',
  'Mathematics',
  'Construction and Extraction',
  'Education',
  'Training',
  'Farming and Fishing',
  'Food Preparation',
  'Healthcare',
  'Healthcare Support',
  'Maintenance, Repair',
  'Legal',
  'Life, Physical Science',
  'Management',
  'Military Specific',
  'Office and Administrative',
  'Personal Care and Service',
  'Production',
  'Protective Service',
  'Sales and Related'
];

export const educationFeilds: string[] = [
  'Archaeology',
  'History',
  'Linguistics and languages',
  'Philosophy',
  'Religion',
  'Culinary arts',
  'Literature',
  'Performing arts',
  'Visual arts',
  'Economics',
  'Geography',
  'Area studies',
  'Ethnic and cultural studies',
  'Gender and sexuality studies',
  'Organizational studies',
  'Political science',
  'Psychology',
  'Sociology',
  'Biology',
  'Chemistry',
  'Earth sciences',
  'Physics',
  'Space sciences',
  'Astronomy',
  'Formal sciences',
  'Computer sciences',
  'Logic',
  'Pure mathematics',
  'Applied mathematics',
  'Statistics',
  'Systems science',
  'Agriculture',
  'Architecture and design',
  'Business',
  'Divinity',
  'Education',
  'Engineering and technology',
  'Law',
  'Library and museum studies',
  'Medicine',
  'Military sciences'
];

export const receiptTypes = ['Income', 'Outcome'];
